name: api-linter-check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Go Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: api/go.mod
          cache-dependency-path: api/go.sum

      - uses: golangci/golangci-lint-action@v8
        with:
          version: v2.13
          working-directory: api
